Repository deepakvk0712/HRManagementSoftware-SoftwareEngineering, pull requests merged in 2022-04, with the labels that each got.

#113 Deepak vuetify changes
  front-end/src/Popups/sendNotification.vue
  front-end/src/components/LandingPage.vue
  front-end/src/store/store.js
Labels: Notification feature

#131 Integrated leave application component with the backend and other tasks.
  front-end/src/Popups/ApplyLeavePopup.vue
  front-end/src/Popups/FinancialFormPopup.vue
  front-end/src/Popups/HRRegisterEmployee.vue
  front-end/src/Popups/OnboardingFormPopup.vue
  front-end/src/Popups/sendNotification.vue
  front-end/src/components/AttendancePage.vue
  front-end/src/components/LandingPage.vue
  front-end/src/store/store.js
  front-end/src/views/UserProfileView.vue
Labels: enhancement, story, Notification feature

#136 Added link to the training page in the navigation bar.
  front-end/src/components/NavigationBar.vue
Labels: enhancement

#137 Designed and developed the resignation popup.
  front-end/src/Popups/resignationPopup.vue
  front-end/src/components/LandingPage.vue
  front-end/tests/e2e/specs/test.js
  front-end/tests/unit/LeaveInformation.spec.js
Labels: story

#144 Deepak vuetify changes
  front-end/src/Popups/resignationPopup.vue
  front-end/tests/unit/resignation.spec.js
Labels: testing

#156 Integrated attendance page with backend.
  front-end/src/Popups/resignationPopup.vue
  front-end/src/components/AttendancePage.vue
Labels: Integration with Backend

#163 Made some changes to the about page.
  front-end/src/Popups/resignationPopup.vue
  front-end/src/assets/background.png
  front-end/src/views/AboutView.vue
Labels: enhancement

#168 Deepak vuetify changes
  front-end/src/Popups/ApplyLeavePopup.vue
  front-end/src/Popups/FinancialFormPopup.vue
  front-end/src/Popups/OnboardingFormPopup.vue
  front-end/src/Popups/resignationPopup.vue
  front-end/src/views/UserProfileView.vue
Labels: enhancement

#171 sprint 4 md file creation
  sprint4.md
Labels: documentation

#173 Sushmitha front end
  front-end/src/components/PayslipPage.vue
  front-end/src/components/Training.vue
  front-end/src/router/index.js
Labels: enhancement, story

#174 Added test cases for the training component
  front-end/src/components/Training.vue
  front-end/tests/unit/Training.spec.js
Labels: testing

#175 Update sprint4.md
  sprint4.md
Labels: documentation

#176 Final changes for sprint 4
  front-end/src/components/LoginPage.vue
  front-end/tests/e2e/specs/test.js
Labels: story

#177 Front end staging
  front-end/src/Popups/ApplyLeavePopup.vue
  front-end/src/Popups/FinancialFormPopup.vue
  front-end/src/Popups/HRRegisterEmployee.vue
  front-end/src/Popups/OnboardingFormPopup.vue
  front-end/src/Popups/resignationPopup.vue
  front-end/src/Popups/sendNotification.vue
  front-end/src/assets/background.png
  front-end/src/components/AttendancePage.vue
  front-end/src/components/LandingPage.vue
  front-end/src/components/LoginPage.vue
  front-end/src/components/NavigationBar.vue
  front-end/src/components/PayslipPage.vue
  front-end/src/components/Training.vue
  front-end/src/router/index.js
  front-end/src/store/store.js
  front-end/src/views/AboutView.vue
  front-end/src/views/UserProfileView.vue
  front-end/tests/e2e/specs/test.js
  front-end/tests/unit/LeaveInformation.spec.js
  front-end/tests/unit/Training.spec.js
  front-end/tests/unit/resignation.spec.js
Labels: documentation, enhancement, story, profile, testing, Notification feature, Integration with Backend

#178 Deepakvk0712 patch 5
  Backend/Controller/ResignationController_test.go
  Backend/Controller/updateController_test.go
  Backend/Controller/workingController_test.go
  Backend/Database/DAO/usersDAO.go
  README.md
  sprint4.md
Labels: documentation

#179 Deepakvk0712 patch 5
  README.md
  sprint4.md
Labels: documentation
